name: Black

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on branch main and develop
  push:
    branches: 
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - name: lint
        run: |
          "black main.py"
          "black lexer_test.py"
          "black parser_text.py"
          "black interpreter_test.py"
          
        
